# Use a imagem oficial do Python como base
FROM python:3.11.6

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de requisitos do Django
COPY back_end/requirements.txt ./

# Instala as dependências do Django
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação
COPY back_end/ .

# Expõe a porta padrão do Django
EXPOSE 8000

# Comando para iniciar o servidor Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
