services:
  front_end:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front_end:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - back_end
    networks:
      - my_network

  back_end:
    container_name: backend
    build: 
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./back_end:/app
    networks:
      - my_network

networks:
  my_network: