version: '3.8'

services:
  front_end:
    build: 
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front_end:/app
    stdin_open: true
    tty: true
    depends_on:
      - back_end

  back_end:
    build: 
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./back_end:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: