version: '3.8'

services:
  front_end:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front_end:/app
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]
    depends_on:
      - back_end
    networks:
      - my_network

  back_end:
    container_name: backend
    build: 
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./back_end:/app
    networks:
      - my_network
    # depends_on:
    #   - db

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

networks:
  my_network: